### ISSUE TITLE
貌似文章加密功能是无法直接使用的

### ISSUE THREAD

**Issue by ghost** [theme-particlex/hexo-theme-particlex#79]
如题，按照您的教程配置好后，如果是执行`hexo s`的话会报错，报错内容大致是（我删减了一些）

```
    51|         ref="crypto"
    52|         placeholder="文章被加密，请输入密码"
 >> 53|         data-encrypted="<%- CryptoJS.AES.encrypt(page.content, page.secret).toString() %>"
    54|         data-shasum="<%- CryptoJS.SHA256(page.content).toString() %>"
    55|         v-model="crypto"
    56|     />
```
如果是执行`hexo g`时，所生成对应的html文件大小是0字节
即使是部署到vercel上问题依旧
~~我尝试多次自行解决这个问题，但是我太菜了，问题并没有解决.......~~

**Comment by argvchs** [comment]
安装插件

**Comment by SaltedFishesNG** [comment]
> 安装插件

在博客的根目录中执行`pnpm add hexo-helper-crypto`的输出结果是

**Comment by argvchs** [comment]
清除缓存

```bash
hexo cl
```

**Comment by SaltedFishesNG** [comment]
> 

仍未解决，报错依旧

**Comment by argvchs** [comment]
完整报错发一下

**Comment by SaltedFishesNG** [comment]
> 完整报错发一下
```

PS C:\Users\SaltedFishes\Documents\Code\blog> hexo s 
INFO  Validating config
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/ . Press Ctrl+C to stop.
Unhandled rejection TypeError: C:\Users\SaltedFishes\Documents\Code\blog\themes\particlex\layout\post.ejs:53
    51|         ref="crypto"
    52|         placeholder="文章被加密，请输入密码"
 >> 53|         data-encrypted="<%- CryptoJS.AES.encrypt(page.content, page.secret).toString() %>"
    54|         data-shasum="<%- CryptoJS.SHA256(page.content).toString() %>"
    55|         v-model="crypto"
    56|     />

Cannot read properties of undefined (reading '0')
    at Object.xorBlock (C:\Users\SaltedFishes\Documents\Code\blog\node_modules\.pnpm\crypto-js@4.1.1\node_modules\crypto-js\cipher-core.js:371:44)
    at Object.processBlock (C:\Users\SaltedFishes\Documents\Code\blog\node_modules\.pnpm\crypto-js@4.1.1\node_modules\crypto-js\cipher-core.js:314:27)
    at Object._doProcessBlock (C:\Users\SaltedFishes\Documents\Code\blog\node_modules\.pnpm\crypto-js@4.1.1\node_modules\crypto-js\cipher-core.js:486:25)
    at Object._process (C:\Users\SaltedFishes\Documents\Code\blog\node_modules\.pnpm\crypto-js@4.1.1\node_modules\crypto-js\core.js:632:27)
    at Object._doFinalize (C:\Users\SaltedFishes\Documents\Code\blog\node_modules\.pnpm\crypto-js@4.1.1\node_modules\crypto-js\cipher-core.js:501:46)
    at Object.finalize (C:\Users\SaltedFishes\Documents\Code\blog\node_modules\.pnpm\crypto-js@4.1.1\node_modules\crypto-js\cipher-core.js:163:44)
    at Object.encrypt (C:\Users\SaltedFishes\Documents\Code\blog\node_modules\.pnpm\crypto-js@4.1.1\node_modules\crypto-js\cipher-core.js:685:41)
    at Object.encrypt (C:\Users\SaltedFishes\Documents\Code\blog\node_modules\.pnpm\crypto-js@4.1.1\node_modules\crypto-js\cipher-core.js:201:59)
    at eval ("C:\\Users\\SaltedFishes\\Documents\\Code\\blog\\themes\\particlex\\layout\\post.ejs":68:30)
    at post (C:\Users\SaltedFishes\Documents\Code\blog\node_modules\.pnpm\ejs@3.1.9\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiled (C:\Users\SaltedFishes\Documents\Code\blog\node_modules\.pnpm\hexo@6.3.0\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (C:\Users\SaltedFishes\Documents\Code\blog\node_modules\.pnpm\hexo@6.3.0\node_modules\hexo\lib\theme\view.js:39:17)
    at C:\Users\SaltedFishes\Documents\Code\blog\node_modules\.pnpm\hexo@6.3.0\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (C:\Users\SaltedFishes\Documents\Code\blog\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\util.js:16:23)
    at C:\Users\SaltedFishes\Documents\Code\blog\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (C:\Users\SaltedFishes\Documents\Code\blog\node_modules\.pnpm\hexo@6.3.0\node_modules\hexo\lib\hexo\router.js:47:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)


```

**Comment by argvchs** [comment]
密码必须是 `string` 类型

**Comment by argvchs** [comment]
啊

**Comment by SaltedFishesNG** [comment]
我密码是在`secret: `后直接衔接密码了，并没有使用引号
