### ISSUE TITLE
请教如何添加插件

### ISSUE THREAD

**Issue by whiteki08** [theme-particlex/hexo-theme-particlex#94]
如题，我想为博客增加[番剧界面插件](https://github.com/HCLonely/hexo-bilibili-bangumi)。

若使用*theme:landscape*可以正常访问localhost:4000/bangumi,使用*theme:particlex*则不能，请问需要修改什么配置。

hexo的报错如下：

    Unhandled rejection TypeError: /Users/*/*/themes/particlex/layout/layout.ejs:48
        46|         <%- partial("menu") %>
        47|         <div id="main" :class="loading ? 'into-enter-from': 'into-enter-active'">
    >> 48|             <%- partial(type) %>
        49|             <%- partial("footer") %>
        50|         </div>
        51|         <% if (theme.preview.enable) { %>

    name must be a string!
        at Object.partial (/Users/*/*/node_modules/hexo/lib/plugins/helper/partial.js:6:39)
        at eval ("/Users/*/*/themes/particlex/layout/layout.ejs":54:17)
        at layout (/Users/*/*/node_modules/ejs/lib/ejs.js:703:17)
        at _View._compiled (/Users/*/*/node_modules/hexo/lib/theme/view.js:136:50)
        at _View.render (/Users/*/*/node_modules/hexo/lib/theme/view.js:39:17)
        at /Users/*/*/node_modules/hexo/lib/theme/view.js:51:25
        at tryCatcher (/Users/*/*/node_modules/bluebird/js/release/util.js:16:23)
        at Promise._settlePromiseFromHandler (/Users/*/*/node_modules/bluebird/js/release/promise.js:547:31)
        at Promise._settlePromise (/Users/*/*/node_modules/bluebird/js/release/promise.js:604:18)
        at Promise._settlePromise0 (/Users/*/*/node_modules/bluebird/js/release/promise.js:649:10)
        at Promise._settlePromises (/Users/*/*/node_modules/bluebird/js/release/promise.js:729:18)
        at _drainQueueStep (/Users/*/*/node_modules/bluebird/js/release/async.js:93:12)
        at _drainQueue (/Users/*/*/node_modules/bluebird/js/release/async.js:86:9)
        at Async._drainQueues (/Users/*/*/node_modules/bluebird/js/release/async.js:102:5)
        at Async.drainQueues [as _onImmediate] (/Users/*/*/node_modules/bluebird/js/release/async.js:15:14)
        at process.processImmediate (node:internal/timers:478:21)

**Comment by zkz098** [comment]
根据源码来看应该是 hexo-bilibili-bangumi 使用了特殊的页面类型，导致 layout 开头的所有if均未被触发，此时type为`undefined`，而非`string`
