### ISSUE TITLE
site.categories.data.forEach is not a function

### ISSUE THREAD

**Issue by FuseFairy** [theme-particlex/hexo-theme-particlex#99]
配置标签会出现下错误，已完全按照教学去设置category和tag，但这2个页面依然没法正常显示，谢谢。
```
ERROR
TypeError: C:\Users\ASUS\github page\FuseFairy.github.io\themes\particlex\layout\categories.ejs:5
    3|     <div class="categories-tags">
    4|         <% let prev; %>
 >> 5|         <% site.categories.data.forEach(category => { %>
    6|         <%
    7|             const colors = is_category(category.name)
    8|                 ? ["linear-gradient(120deg, #9abbf7 0%, #ffbbf4 100%)"]

site.categories.data.forEach is not a function
    at eval (eval at compile (C:\Users\ASUS\github page\FuseFairy.github.io\node_modules\ejs\lib\ejs.js:673:12), <anonymous>:18:29)
    at categories (C:\Users\ASUS\github page\FuseFairy.github.io\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiled (C:\Users\ASUS\github page\FuseFairy.github.io\node_modules\hexo\dist\theme\view.js:125:67)
    at _View.render (C:\Users\ASUS\github page\FuseFairy.github.io\node_modules\hexo\dist\theme\view.js:50:21)
    at C:\Users\ASUS\github page\FuseFairy.github.io\node_modules\hexo\dist\hexo\index.js:58:29
    at tryCatcher (C:\Users\ASUS\github page\FuseFairy.github.io\node_modules\bluebird\js\release\util.js:16:23)
    at C:\Users\ASUS\github page\FuseFairy.github.io\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (C:\Users\ASUS\github page\FuseFairy.github.io\node_modules\hexo\dist\hexo\router.js:43:9)
    at Readable.read (node:internal/streams/readable:547:12)
    at resume_ (node:internal/streams/readable:1048:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by uchzmal** [comment]
同上
```
Microsoft Windows [版本 10.0.19045.3448]
(c) Microsoft Corporation。保留所有权利。

V:\zmal>hexo g
INFO  Validating config
INFO  Start processing
INFO  Files loaded in 652 ms
ERROR Render HTML failed: tags/发病/index.html
TypeError: V:\zmal\themes\particlex\layout\layout.ejs:40
    38|         <%- partial("menu") %>
    39|         <div id="main" :class="loading ? 'into-enter-from': 'into-enter-active'">
 >> 40|             <%- partial(type) %>
    41|             <%- partial("footer") %>
    42|         </div>
    43|         <% if (theme.preview.enable) { %>

V:\zmal\themes\particlex\layout\tags.ejs:5
    3|     <div class="categories-tags">
    4|         <% let prev; %>
 >> 5|         <% site.tags.data.forEach(tag => { %>
    6|         <%
    7|             const colors = is_tag(tag.name)
    8|                 ? ["linear-gradient(120deg, #9abbf7 0%, #ffbbf4 100%)"]

site.tags.data.forEach is not a function
    at eval ("V:\\zmal\\themes\\particlex\\layout\\tags.ejs":18:23)
    at tags (V:\zmal\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiledSync (V:\zmal\node_modules\hexo\dist\theme\view.js:122:32)
    at _View.renderSync (V:\zmal\node_modules\hexo\dist\theme\view.js:64:29)
    at Object.partial (V:\zmal\node_modules\hexo\dist\plugins\helper\partial.js:27:17)
    at eval ("V:\\zmal\\themes\\particlex\\layout\\layout.ejs":54:17)
    at layout (V:\zmal\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiled (V:\zmal\node_modules\hexo\dist\theme\view.js:125:67)
    at _View.render (V:\zmal\node_modules\hexo\dist\theme\view.js:50:21)
    at V:\zmal\node_modules\hexo\dist\theme\view.js:57:31
    at tryCatcher (V:\zmal\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (V:\zmal\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (V:\zmal\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (V:\zmal\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (V:\zmal\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (V:\zmal\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (V:\zmal\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (V:\zmal\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (V:\zmal\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:471:21)
ERROR Render HTML failed: tags/教程/index.html
TypeError: V:\zmal\themes\particlex\layout\layout.ejs:40
    38|         <%- partial("menu") %>
    39|         <div id="main" :class="loading ? 'into-enter-from': 'into-enter-active'">
 >> 40|             <%- partial(type) %>
    41|             <%- partial("footer") %>
    42|         </div>
    43|         <% if (theme.preview.enable) { %>

V:\zmal\themes\particlex\layout\tags.ejs:5
    3|     <div class="categories-tags">
    4|         <% let prev; %>
 >> 5|         <% site.tags.data.forEach(tag => { %>
    6|         <%
    7|             const colors = is_tag(tag.name)
    8|                 ? ["linear-gradient(120deg, #9abbf7 0%, #ffbbf4 100%)"]

site.tags.data.forEach is not a function
    at eval ("V:\\zmal\\themes\\particlex\\layout\\tags.ejs":18:23)
    at tags (V:\zmal\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiledSync (V:\zmal\node_modules\hexo\dist\theme\view.js:122:32)
    at _View.renderSync (V:\zmal\node_modules\hexo\dist\theme\view.js:64:29)
    at Object.partial (V:\zmal\node_modules\hexo\dist\plugins\helper\partial.js:27:17)
    at eval ("V:\\zmal\\themes\\particlex\\layout\\layout.ejs":54:17)
    at layout (V:\zmal\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiled (V:\zmal\node_modules\hexo\dist\theme\view.js:125:67)
    at _View.render (V:\zmal\node_modules\hexo\dist\theme\view.js:50:21)
    at V:\zmal\node_modules\hexo\dist\theme\view.js:57:31
    at tryCatcher (V:\zmal\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (V:\zmal\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (V:\zmal\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (V:\zmal\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (V:\zmal\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (V:\zmal\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (V:\zmal\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (V:\zmal\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (V:\zmal\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:471:21)
ERROR
TypeError: V:\zmal\themes\particlex\layout\layout.ejs:40
    38|         <%- partial("menu") %>
    39|         <div id="main" :class="loading ? 'into-enter-from': 'into-enter-active'">
 >> 40|             <%- partial(type) %>
    41|             <%- partial("footer") %>
    42|         </div>
    43|         <% if (theme.preview.enable) { %>

V:\zmal\themes\particlex\layout\tags.ejs:5
    3|     <div class="categories-tags">
    4|         <% let prev; %>
 >> 5|         <% site.tags.data.forEach(tag => { %>
    6|         <%
    7|             const colors = is_tag(tag.name)
    8|                 ? ["linear-gradient(120deg, #9abbf7 0%, #ffbbf4 100%)"]

site.tags.data.forEach is not a function
    at eval ("V:\\zmal\\themes\\particlex\\layout\\tags.ejs":18:23)
    at tags (V:\zmal\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiledSync (V:\zmal\node_modules\hexo\dist\theme\view.js:122:32)
    at _View.renderSync (V:\zmal\node_modules\hexo\dist\theme\view.js:64:29)
    at Object.partial (V:\zmal\node_modules\hexo\dist\plugins\helper\partial.js:27:17)
    at eval ("V:\\zmal\\themes\\particlex\\layout\\layout.ejs":54:17)
    at layout (V:\zmal\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiled (V:\zmal\node_modules\hexo\dist\theme\view.js:125:67)
    at _View.render (V:\zmal\node_modules\hexo\dist\theme\view.js:50:21)
    at V:\zmal\node_modules\hexo\dist\theme\view.js:57:31
    at tryCatcher (V:\zmal\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (V:\zmal\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (V:\zmal\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (V:\zmal\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (V:\zmal\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (V:\zmal\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (V:\zmal\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (V:\zmal\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (V:\zmal\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:471:21)
ERROR
TypeError: V:\zmal\themes\particlex\layout\layout.ejs:40
    38|         <%- partial("menu") %>
    39|         <div id="main" :class="loading ? 'into-enter-from': 'into-enter-active'">
 >> 40|             <%- partial(type) %>
    41|             <%- partial("footer") %>
    42|         </div>
    43|         <% if (theme.preview.enable) { %>

V:\zmal\themes\particlex\layout\tags.ejs:5
    3|     <div class="categories-tags">
    4|         <% let prev; %>
 >> 5|         <% site.tags.data.forEach(tag => { %>
    6|         <%
    7|             const colors = is_tag(tag.name)
    8|                 ? ["linear-gradient(120deg, #9abbf7 0%, #ffbbf4 100%)"]

site.tags.data.forEach is not a function
    at eval ("V:\\zmal\\themes\\particlex\\layout\\tags.ejs":18:23)
    at tags (V:\zmal\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiledSync (V:\zmal\node_modules\hexo\dist\theme\view.js:122:32)
    at _View.renderSync (V:\zmal\node_modules\hexo\dist\theme\view.js:64:29)
    at Object.partial (V:\zmal\node_modules\hexo\dist\plugins\helper\partial.js:27:17)
    at eval ("V:\\zmal\\themes\\particlex\\layout\\layout.ejs":54:17)
    at layout (V:\zmal\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiled (V:\zmal\node_modules\hexo\dist\theme\view.js:125:67)
    at _View.render (V:\zmal\node_modules\hexo\dist\theme\view.js:50:21)
    at V:\zmal\node_modules\hexo\dist\theme\view.js:57:31
    at tryCatcher (V:\zmal\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (V:\zmal\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (V:\zmal\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (V:\zmal\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (V:\zmal\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (V:\zmal\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (V:\zmal\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (V:\zmal\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (V:\zmal\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:471:21)
INFO  Generated: 2023/06/18/雷电模拟器去广告教程/index.html
INFO  Generated: 2023/10/28/人生三大错觉：下一发出金，我能反杀，她喜欢我/index.html
INFO  Generated: 2023/06/16/366年/index.html
INFO  Generated: 2023/09/29/pc端利用cmd实现定时关机/index.html
INFO  Generated: archives/2023/06/index.html
INFO  Generated: archives/index.html
INFO  Generated: archives/2023/index.html
INFO  Generated: archives/2023/08/index.html
INFO  Generated: archives/2023/09/index.html
INFO  Generated: archives/2023/10/index.html
INFO  Generated: archives/2023/11/index.html
INFO  Generated: index.html
INFO  Generated: 2023/08/14/基于GitHub-pages-hexo-搭建个人博客/index.html
INFO  13 files generated in 214 ms
```

**Comment by zkz098** [comment]
https://github.com/hexojs/hexo/issues/5367
Hexo v7版本已知问题，主题使用了非规范属性导致的，等hexo修复或者换成标准的Query获取

**Comment by zkz098** [comment]
此Issue内解决方法会导致cat.path丢失（即分类无法跳转到对应链接）
@argvchs 建议添加对hexo v7的不兼容说明

**Comment by FuseFairy** [comment]
已解决，谢谢
